esphome:
  name: esp-dsmr-cc2652-poe
  on_boot:
    priority: 600
    then:
      - switch.turn_on: zRST_gpio


esp32:
  board: esp32-poe-iso
  framework:
    type: arduino

#captive_portal:

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12

  manual_ip:
    static_ip: x.x.x.235
    gateway:
    subnet:
    dns1:

api:
  reboot_timeout: 0s
  
logger:
#  level: VERBOSE
#  baud_rate: 0

ota:

mqtt:
  broker:
  username:
  password:
  client_id: esp-dsmr-cc2652-poe
  discovery: true
  discovery_retain: true
  
esp32_ble_tracker:

uart:
  - rx_pin:
      number: 16
      inverted: true
    rx_buffer_size: 1700
    baud_rate: 115200
    id: uart_dsmr
  - rx_pin: GPIO3
    tx_pin: GPIO1
    baud_rate: 115200
    id: uart_zigbee

dsmr:
  max_telegram_length: 1700
  crc_check: true
  uart_id: uart_dsmr
  
sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: "Energy Consumed Tariff 1"
    energy_delivered_tariff2:
      name: "Energy Consumed Tariff 2"
    energy_returned_tariff1:
      name: "Energy Produced Tariff 1"
    energy_returned_tariff2:
      name: "Energy Produced Tariff 2"
    power_delivered:
      name: "Power Consumed"
      accuracy_decimals: 3
    power_returned:
      name: "Power Produced"
      accuracy_decimals: 3
    electricity_failures:
      name: "Electricity Failures"
      icon: mdi:alert
    electricity_long_failures:
      name: "Long Electricity Failures"
      icon: mdi:alert
    voltage_l1:
      name: "Voltage Phase 1"
    voltage_l2:
      name: "Voltage Phase 2"
    voltage_l3:
      name: "Voltage Phase 3"
    current_l1:
      name: "Current Phase 1"
    current_l2:
      name: "Current Phase 2"
    current_l3:
      name: "Current Phase 3"
    power_delivered_l1:
      name: "Power Consumed Phase 1"
      accuracy_decimals: 3
    power_delivered_l2:
      name: "Power Consumed Phase 2"
      accuracy_decimals: 3
    power_delivered_l3:
      name: "Power Consumed Phase 3"
      accuracy_decimals: 3
    power_returned_l1:
      name: "Power Produced Phase 1"
      accuracy_decimals: 3
    power_returned_l2:
      name: "Power Produced Phase 2"
      accuracy_decimals: 3
    power_returned_l3:
      name: "Power Produced Phase 3"
      accuracy_decimals: 3
    gas_delivered:
      name: "Gas Consumed"
  - platform: uptime
    name: "SlimmeLezer Uptime"

text_sensor:
  - platform: dsmr
    identification:
      name: "DSMR Identification"
    p1_version:
      name: "DSMR Version"
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: false

web_server:
  port: 80

script:
  - id: fw_update_mode
    then:
      - switch.turn_on: zBSL
      - delay: 1s
      - switch.turn_on: zRST_gpio
#      - delay: 1s
#      - switch.turn_off: zRST_gpio
      - logger.log: "Delaying ~10 seconds for cc2652p2 to settle"
      - delay: 11s
      - switch.turn_off: zBSL
      - logger.log: "Please try update with cc-bsl tool now"
      - logger.log: "cc-bsl usage: cc-bsl.py -p socket://ip-of-gw:6638 -evw firmware.hex"
      
switch:
  - platform: restart
    name: "Restart the Gateway"

  - platform: gpio
    pin: 13
    id: zRST_gpio
    inverted: yes
    restore_mode: ALWAYS_OFF
    name: zRST
    on_turn_on:
      - delay: 100ms
      - switch.turn_off: zRST_gpio
      
  - platform: gpio
    pin: 5
    name: "zBSL"
    id: zBSL
    inverted: yes
    restore_mode: ALWAYS_OFF
    
  - platform: template
    name: "Prep the cc2652p2 for firmware update"
    turn_on_action:
      - script.execute: fw_update_mode
    turn_off_action:
      - switch.toggle: zRST_gpio

#serial_server:
#  port: 6638
#  multi_client: false 
  
#binary_sensor:
#  - platform: serial_server
#    name: Serial Connected
    
#zeroconf:
#  - service: tubeszb
#    protocol: tcp
#    port: 6638
#    txt:
#      version: 1.0
#      port: 6638
#      radio_type: znp
#      baud_rate: 115200
#      data_flow_control: software
